name: Checkov Testing

on:
  push:
    branches: main
  
jobs:
  security-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v2
      - name: Checkov testing 
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./02-webapp/
          framework: terraform