name: Checkov Testing

on:
  push:
    branches: main
  
jobs:
  build:
    - runs-on: ubuntu-latest
    - steps:
      - uses: actions/checkout@v2
    # - uses: devsecopsacademy/checkov:2.0.241
        - run: cd ./02-webapp
        - run: apt install checkov 
        - run: checkov -d . --framework terraform --output cli --quiet --skip-check CKV_AWS_20,CKV_AWS_21
